services:
  - type: web
    name: onemax-backend
    env: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    autoDeploy: true
